title:            Scribble
description:      A jekyll theme. Because I scribble.
url:              http://evilmuan.github.io/scribble
signoff:          Mu-An Evil™
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://evilmuan.github.io/scribble
    external:     true
  - name:         GitHub
    url:          http://github.com/evilmuan
    external:     true
  - name:         My friend @jlord
    url:          http://github.com/jlord
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
